AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: subnet-watcher - publishes VPC subnet IP metrics to CloudWatch

Parameters:
  pEnv:
    Type: String
  pAWSRegion:
    Type: String
  pProjectName:
    Type: String
  pProductName:
    Type: String
  pDescription:
    Type: String

Resources:
  Function:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub ${pProjectName}-${pProductName}-${pEnv}
      Description: !Ref pDescription
      Handler: handlers.main
      Runtime: python3.9
      CodeUri: ./python/
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(*/5 * * * ? *)
      MemorySize: 256
      Timeout: 300
      Environment:
        Variables:
          VPC_ID: ""
          REGION_ID: !Ref pAWSRegion
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeNetworkInterfaces
                - ec2:DescribeSubnets
                - ec2:DescribeVpcs
                - ec2:DescribeVpcAttribute
                - ec2:DescribeRegions
                - cloudwatch:PutMetricData
              Resource: "*"
      Tags:
        Project: !Ref pProjectName
        Product: !Ref pProductName
        Environment: !Ref pEnv

  LambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${pProjectName}-${pProductName}-${pEnv}"
      RetentionInDays: 30
